version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: goldwen_postgres
    environment:
      POSTGRES_DB: goldwen_db
      POSTGRES_USER: goldwen
      POSTGRES_PASSWORD: goldwen_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U goldwen -d goldwen_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: goldwen_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  matching-service:
    build:
      context: ./matching-service
      dockerfile: Dockerfile
    container_name: goldwen_matching_service
    environment:
      API_KEY: matching-service-secret-key
      DATABASE_URL: postgresql://goldwen:goldwen_password@postgres:5432/goldwen_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      CACHE_TTL: 3600
      CACHE_ENABLED: "true"
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: goldwen_network