version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: goldwen_postgres
    environment:
      POSTGRES_DB: goldwen_db
      POSTGRES_USER: goldwen
      POSTGRES_PASSWORD: goldwen_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U goldwen -d goldwen_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: goldwen_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Main API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: goldwen_api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=goldwen
      - DATABASE_PASSWORD=goldwen_password
      - DATABASE_NAME=goldwen_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MATCHING_SERVICE_URL=http://matching-service:8000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./main-api/uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Matching Service
  matching-service:
    build:
      context: .
      dockerfile: Dockerfile.matching
    container_name: goldwen_matching
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://goldwen:goldwen_password@postgres:5432/goldwen_db
      - REDIS_URL=redis://redis:6379
      - MAIN_API_URL=http://api:3000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: goldwen_network