version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: goldwen_postgres
    environment:
      POSTGRES_DB: goldwen_db
      POSTGRES_USER: goldwen
      POSTGRES_PASSWORD: goldwen_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U goldwen -d goldwen_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: goldwen_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: goldwen_network